GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJJbGhhbSBNdWhhbW1hZCIsImVtYWlsIjoiaWxoYW1oZDk4QGdtYWlsLmNvbSIsImlhdCI6MTY1MDQzMzA3OSwiZXhwIjoxNjUwNDMzMDk0fQ.MqrHGiJFSRishTIIN_FdDlpRKwRzi7egFwygdhUYRE8

###
GET http://localhost:5000/users/2

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Ilham Muhammad",
    "username": "ilhamhmmd",
    "gender": "male"
}

###
PATCH http://localhost:5000/users/2
Content-Type: application/json

{
    "name": "Bambang",
    "username": "bambang@gmail.com",
    "gender": "male"
}

###
DELETE  http://localhost:5000/users/5

###
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "Ilham Muhammad",
    "username": "ilhamhmmd",
    "password": "ilham@123",
    "confPassword": "ilham@123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "ilhamhmmd",
    "password": "qwqwqw"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

###
GET http://localhost:5000/weathers